### ISSUE TITLE
Gradle Build Error - Unable to Find Valid Docker Environment...

### ISSUE THREAD

**Issue by takuhii** [Netflix/maestro#29]
```
> ./gradlew build

> Task :cockroachdb-persistence:test

CockroachDBEventHandlerDAOTest > classMethod FAILED
    com.zaxxer.hikari.pool.HikariPool$PoolInitializationException at HikariPool.java:596
        Caused by: java.lang.IllegalStateException at DockerClientProviderStrategy.java:277

CockroachDBExecutionDAOTest > classMethod FAILED
    com.zaxxer.hikari.pool.HikariPool$PoolInitializationException at HikariPool.java:596
        Caused by: java.lang.IllegalStateException at DockerClientProviderStrategy.java:232

CockroachDBIndexDAOTest > classMethod FAILED
    com.zaxxer.hikari.pool.HikariPool$PoolInitializationException at HikariPool.java:596
        Caused by: java.lang.IllegalStateException at DockerClientProviderStrategy.java:232

CockroachDBMetadataDAOTest > classMethod FAILED
    com.zaxxer.hikari.pool.HikariPool$PoolInitializationException at HikariPool.java:596
        Caused by: java.lang.IllegalStateException at DockerClientProviderStrategy.java:232

CockroachDBPollDataDAOTest > classMethod FAILED
    com.zaxxer.hikari.pool.HikariPool$PoolInitializationException at HikariPool.java:596
        Caused by: java.lang.IllegalStateException at DockerClientProviderStrategy.java:232

CockroachDBRateLimitingDAOTest > classMethod FAILED
    com.zaxxer.hikari.pool.HikariPool$PoolInitializationException at HikariPool.java:596
        Caused by: java.lang.IllegalStateException at DockerClientProviderStrategy.java:232

6 tests completed, 6 failed

> Task :cockroachdb-persistence:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cockroachdb-persistence:test'.
```

When I investigate the logs
`com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not find a valid Docker environment. Please see logs and check configuration
`

I have Docker installed, Java 21 and 22 (jenv controlled), latest Gradle 8.9 and latest Docker. I interact with docker via Colima as I am using an M3 Mac. Could someone point me in the right direction to get this up and running please?

**Comment by jun-he** [comment]
@takuhii can you try `./gradlew bootRun` to see what happens?

**Comment by jun-he** [comment]
Also, in your build terminal, what's the result if you type `docker ps`?

**Comment by jun-he** [comment]
Maestro uses testcontainers, you might follow this to set it up for colima
https://java.testcontainers.org/supported_docker_environment/#using-colima

**Comment by takuhii** [comment]
> @takuhii can you try `./gradlew bootRun` to see what happens?

I get the same failure message

**Comment by takuhii** [comment]
> Also, in your build terminal, what's the result if you type `docker ps`?

`docker ps` is empty, no containers

**Comment by jun-he** [comment]
@takuhii  Got it. have you tried https://github.com/Netflix/maestro/issues/29#issuecomment-2248864645?

**Comment by takuhii** [comment]
It was Colima and the TEST_CONTAINERS. This seems to have resolved it, thank you...
