### ISSUE TITLE
Is maestro planning to introduce ES to enhance search capabilities? Or use corkroach to support retrieval?

### ISSUE THREAD

**Issue by bearlly** [Netflix/maestro#68]
Is maestro planning to introduce ES to enhance search capabilities? Or use corkroach to support retrieval?

**Comment by jun-he** [comment]
@bearlly If it is free text search, it's better to use ES. As maestro publishes a change event for any status changes of step and workflow, it is straightforward to build an ES ingestion pipeline to create a search index for those cases. 

Additionally, Maestro DB is highly optimized for the execution. It is efficient to do a point query and some range queries to support some key search features related to the execution.

**Comment by jun-he** [comment]
@bearlly let me know if you have any additional questions before I close the issue. Thanks.
