### ISSUE TITLE
Getting this error while running Gradlew build command -"> Task :cockroachdb-persistence:spotlessJavaCheck FAILED"

### ISSUE THREAD

**Issue by vishnu19951295** [Netflix/maestro#72]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cockroachdb-persistence:spotlessJavaCheck'.
> The following files had format violations:
      src\main\java\com\netflix\conductor\cockroachdb\CockroachDBConfiguration.java
          @@ -1,187 +1,187 @@
          -/*\n
          - * Copyright 2024 Netflix, Inc.\n
          - *\n
          - * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with\n
          - * the License. You may obtain a copy of the License at\n
          - *\n
          - * http://www.apache.org/licenses/LICENSE-2.0\n
          - *\n
          - * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on\n
          - * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the\n
          - * specific language governing permissions and limitations under the License.\n
          - */\n
          -package com.netflix.conductor.cockroachdb;\n
          -\n
          -import com.netflix.conductor.core.config.Configuration;\n
          -import java.util.Optional;\n
          -import java.util.concurrent.TimeUnit;\n
          -\n
          -public interface CockroachDBConfiguration extends Configuration {\n
          -\n
          -  String JDBC_URL_PROPERTY_NAME = "jdbc.url";\n
          -  String JDBC_URL_DEFAULT_VALUE = "jdbc:postgresql://localhost:5432/conductor";\n
          -\n
          -  String JDBC_USER_NAME_PROPERTY_NAME = "jdbc.username";\n
          -  String JDBC_USER_NAME_DEFAULT_VALUE = "conductor";\n
          -\n
          -  String JDBC_PASSWORD_PROPERTY_NAME = "jdbc.password";\n
          -  String JDBC_PASSWORD_DEFAULT_VALUE = "password";\n
          -\n
          -  String FLYWAY_ENABLED_PROPERTY_NAME = "flyway.enabled";\n
          -  boolean FLYWAY_ENABLED_DEFAULT_VALUE = true;\n
          -\n
          -  String FLYWAY_BASELINE_MIGRATION_ENABLED_PROPERTY_NAME = "flyway.baseline.migration.enabled";\n
          -  boolean FLYWAY_BASELINE_MIGRATION_ENABLED_DEFAULT_VALUE = false;\n
          -\n
          -  String FLYWAY_TABLE_PROPERTY_NAME = "flyway.table";\n
          -\n
          -  // The defaults are currently in line with the HikariConfig defaults, which are unfortunately\n
          -  // private.\n
          -  String CONNECTION_POOL_MAX_SIZE_PROPERTY_NAME = "workflow.cockroachdb.connection.pool.size.max";\n
          -  int CONNECTION_POOL_MAX_SIZE_DEFAULT_VALUE = -1;\n
          -\n
          -  String CONNECTION_POOL_MINIMUM_IDLE_PROPERTY_NAME =\n
          -      "workflow.cockroachdb.connection.pool.idle.min";\n
          -  int CONNECTION_POOL_MINIMUM_IDLE_DEFAULT_VALUE = -1;\n
          -\n
          -  String CONNECTION_MAX_LIFETIME_PROPERTY_NAME = "workflow.cockroachdb.connection.lifetime.max";\n
          -  long CONNECTION_MAX_LIFETIME_DEFAULT_VALUE = TimeUnit.MINUTES.toMillis(30);\n
      ... (326 more lines that didn't fit)
  Violations also present in 21 other files.
  Run 'gradlew.bat :cockroachdb-persistence:spotlessApply' to fix these violations.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 8s
9 actionable tasks: 9 executed

I also tried to run this command -  'gradlew.bat :cockroachdb-persistence:spotlessApply'
but then when I run the command gradlew bootrun then my server is stuck at 95% executing. Can you please help me?

**Comment by vishnu19951295** [comment]
My Java version is - java 21.0.4 2024-07-16 LTS
Java(TM) SE Runtime Environment (build 21.0.4+8-LTS-274)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.4+8-LTS-274, mixed mode, sharing)

Gradle version -
Gradle 8.9
------------------------------------------------------------

Build time:    2024-07-11 14:37:41 UTC
Revision:      d536ef36a19186ccc596d8817123e5445f30fef8

Kotlin:        1.9.23
Groovy:        3.0.21
Ant:           Apache Ant(TM) version 1.10.13 compiled on January 4 2023
Launcher JVM:  21.0.4 (Oracle Corporation 21.0.4+8-LTS-274)
Daemon JVM:    C:\Program Files\Java\jdk-21 (no JDK specified, using current Java home)
OS:            Windows 10 10.0 amd64

**Comment by jun-he** [comment]
Can you try `./gradlew -version` and paste the version info here? 
Then can you also try `./gradlew bootRun`? Does it work?

**Comment by vishnu19951295** [comment]
This issue is resolved. 
Thanks for the response.
I also want to know if we have some UI for maestro where in we can see the definations , executions  and is there any detail documentation to see how can we add loops, parallel execution , wait for an external task to trigger the execution ?

**Comment by jun-he** [comment]
@vishnu19951295 We have this issue to track the UI work #3 and another issue #13 for additional execution tasks.
Foreach loop and parallel executions are already included. BTW, the maestro wiki has an simple example including subworkflow and foreach.
I will add more examples (#18) to demo them.

**Comment by jun-he** [comment]
Will close the issue if no more comments.

**Comment by vishnu19951295** [comment]
@jun-he Are the new docs ready?

**Comment by jun-he** [comment]
Not yet. I am currently updating the core engine components, which dramatically improve the performance. After that, I will work on the doc. Thanks.
